export const PATH_COMMAND_COMMANDS = [
  'a',
  'A',
  'C',
  'c',
  'H',
  'h',
  'L',
  'l',
  'M',
  'm',
  'Q',
  'q',
  'S',
  's',
  'T',
  't',
  'V',
  'v',
  'Z',
  'z',
] as const

export const PATH_COMMAND_SEPARATOR = [' ', ','] as const

export const PATH_COMMAND_PARAMS_MAP = {
  A: ['rx', 'ry', 'xAxisRotation', 'largeArcFlag', 'sweepFlag', 'x', 'y'],
  a: ['rx', 'ry', 'xAxisRotation', 'largeArcFlag', 'sweepFlag', 'dx', 'dy'],
  C: ['x1', 'y1', 'x2', 'y2', 'x', 'y'],
  c: ['dx1', 'dy1', 'dx2', 'dy2', 'dx', 'dy'],
  H: ['x'],
  h: ['dx'],
  L: ['x', 'y'],
  l: ['dx', 'dy'],
  M: ['x', 'y'],
  m: ['dx', 'dy'],
  Q: ['x1', 'y1', 'x', 'y'],
  q: ['dx1', 'dy1', 'dx', 'dy'],
  S: ['x2', 'y2', 'x', 'y'],
  s: ['dx2', 'dy2', 'dx', 'dy'],
  T: ['x', 'y'],
  t: ['dx', 'dy'],
  V: ['y'],
  v: ['dy'],
  Z: [],
  z: [],
} as const
